const GENRES: Record<number, string> = {
    1: "Action",
    2: "Adventure",
    5: "Avant Garde",
    28: "Boys Love",
    4: "Comedy",
    8: "Drama",
    10: "Fantasy",
    26: "Girls Love",
    47: "Gourmet",
    14: "Horror",
    7: "Mystery",
    22: "Romance",
    24: "Sci-Fi",
    36: "Slice of Life",
    30: "Sports",
    41: "Suspense",
    37: "Supernatural",
    46: "Award Winning",
};

const EXPLICIT_GENRES: Record<number, string> = {
    9: "Ecchi",
    12: "Hentai",
    49: "Erotica",
};

const DEMOGRAPHICS: Record<number, string> = {
    43: "Josei",
    15: "Kids",
    42: "Seinen",
    25: "Shoujo",
    27: "Shounen",
};

const THEMES: Record<number, string> = {
    3: "Racing",
    6: "Mythology",
    11: "Strategy Game",
    13: "Historical",
    17: "Martial Arts",
    18: "Mecha",
    19: "Music",
    20: "Parody",
    21: "Samurai",
    23: "School",
    29: "Space",
    31: "Super Power",
    32: "Vampire",
    35: "Harem",
    38: "Military",
    39: "Detective",
    40: "Psychological",
    48: "Workplace",
    50: "Adult Cast",
    51: "Anthropomorphic",
    52: "CGDCT",
    53: "Childcare",
    54: "Combat Sports",
    55: "Delinquents",
    56: "Educational",
    57: "Gag Humor",
    58: "Gore",
    59: "High Stakes Game",
    60: "Idols (Female)",
    61: "Idols (Male)",
    62: "Isekai",
    63: "Iyashikei",
    64: "Love Polygon",
    65: "Magical Sex Shift",
    66: "Mahou Shoujo",
    67: "Medical",
    68: "Organized Crime",
    69: "Otaku Culture",
    70: "Performing Arts",
    71: "Pets",
    72: "Reincarnation",
    73: "Reverse Harem",
    74: "Love Status Quo",
    75: "Showbiz",
    76: "Survival",
    77: "Team Sports",
    78: "Time Travel",
    79: "Video Game",
    80: "Visual Arts",
    81: "Crossdressing",
    82: "Urban Fantasy",
    83: "Villainess",
};

export const Constants = Object.freeze({
    genres: GENRES,
    explicitGenres: EXPLICIT_GENRES,
    demographics: DEMOGRAPHICS,
    themes: THEMES,
});